#!/bin/sh
alias ns='npm install --save'
alias nd='npm install --save-dev'
alias ng='npm install -g'
alias ni='npm install'
alias ung='npm uninstall -g'
alias uni='npm uninstall --save-dev'
alias uns='npm uninstall --save'
alias nlg='npm list -g --depth=0'
alias nl='npm list --depth=0'
