#!/usr/local/bin/zsh
# This hook is sourced after a new virtualenv is activated.

pip install --upgrade pip
pip install --upgrade setuptools
pip install -r ~/.virtualenvs/py-deps.txt
nodeenv -p
npm install -g npm
